Repository OpenSourceEconomics/soepy, pull requests merged in 2019-03, with the labels that each got.

#13 Added Simulation Demonstration notebook to documentation.
  doc/source/conf.py
  doc/source/data_frame_sim_test_analysis.ipynb
  doc/source/developer_docs.rst
  doc/source/index.rst
  requirements.txt
Labels: pb documentation

#37 small issues
  soepy/python/soepy_config.py
  soepy/test/test_quality.py
Labels: pb package, priority low, size small

#43 Changed travis notification settings according to our new workflow
  .travis.yml
Labels: size small
